import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>My Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Link href="./auth/register">
          ユーザー登録
        </Link>
        <Link href="./auth/login">
          ログイン
        </Link>
      </header>
      <main className={styles.main}>
        <Link href="/area/europe">
          ヨーロッパ
        </Link>
        <Link href="/area/asiaOceania">
          アジア・オセアニア
        </Link>
        <Link href="/area/africa">
          アフリカ
        </Link>
        <Link href="/area/northAmerica">
          北米
        </Link>
        <Link href="/area/southAmerica">
          南米
        </Link>
        <Link href="/area/antarctic">
          南極
        </Link>
      </main>
    </>
  )
}

